name: Analysis

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
  workflow_dispatch:

jobs:
  # https://github.com/github/codeql-action
  codeql:
    name: CodeQL
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
    
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
