name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-output.outputs.image-tag }}
    steps:
      - name: Set output
        id: set-output
        run: echo "image-tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"
      - name: Print Github output
        run: echo "$GITHUB_OUTPUT"

