name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "test-5"
          echo "first rebase"
      - name: Set output
        id: set-output
        run: echo "::set-output name=image-tag::${{ github.sha }}"
    outputs:
      image-tag: ${{ steps.set-output.outputs.image-tag }}
