name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print image tag
        run: echo "${{ needs.build.outputs.image-tag }}"
