name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag-output: ${{ steps.set-output.outputs.image-tag }}
      commit-hash: ${{ steps.commit-hash.git-sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Git commit hash
        id: commit-hash
        run: echo "git-sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Set output
        id: set-output
        run: echo "image-tag=${{ github.event.number }}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print image tag
        run: echo "${{ needs.build.outputs.image-tag-output }}"
      - name: Print Git commit hash
        run: echo "${{ needs.build.outputs.commit-hash }}"

