name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

concurrency:
  # Cancel in progress for PR open and close, but not merge_group
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      pr-number: ${{ steps.extract-pr-number.outputs.pr-number }}
      short-commit-hash: ${{ steps.extract-commit-hash.outputs.git-sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Git commit hash
        id: extract-commit-hash
        run: echo "git-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set output
        id: extract-pr-number
        run: echo "pr-number=${{ github.event.number }}" >> $GITHUB_OUTPUT
      - name: Print Git commit hash
        run: echo "${{ steps.extract-commit-hash.outputs.git-sha }}" > "outputs.txt"
      - name: Setup artifactory
        uses: jfrog/setup-jfrog-cli@v4
      - name: Push output to Artifactory
        run: jf rt upload  --url ${{ secrets.ARTIFACTORY_URL }} --user ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }} --password ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }} "outputs.txt" ${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print pr number
        run: echo "${{ needs.build.outputs.pr-number }}"
      - name: Print Git commit hash
        run: echo "${{ needs.build.outputs.short-commit-hash }}"
