name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch: # This allows you to manually trigger the workflow

concurrency:
  # Cancel in progress for PR open and close, but not merge_group
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-output.outputs.image-tag }}
      commit-hash: ${{ steps.commit-hash.outputs.git-sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Git commit hash
        id: commit-hash
        run: echo "git-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set output
        id: set-output
        run: echo "image-tag=${{ github.event.number }}" >> $GITHUB_OUTPUT
      - name: Print Git commit hash
        run: echo "${{ build.outputs.commit-hash }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print image tag
        run: echo "${{ needs.build.outputs.image-tag }}"
      - name: Print Git commit hash
        run: echo "${{ needs.build.outputs.commit-hash }}" > output.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-output
          path: output.txt
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-output
          path: .

      - name: Read and use output
        run: |
          cat output.txt
