name: Stage Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get PR from API
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api
          PR=$(gh api /repos/zimimi/simple-python-flask/commits/${{ github.sha }}/pulls | jq -r '.[0].number')
          echo "$PR"
        env:
          GH_TOKEN: ${{ github.token }}
