name: Stage Deployment

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Git commit hash
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Print git sha
        run: echo "${{ env.GIT_SHA }}"
